language: python
python:
- '2.7'
- '3.5'
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
- pip install -r tst_requirements.txt
script:
- cd rhtemp_si7021
- python -m unittest discover -s tst/
- cd ..
deploy:
  provider: pypi
  user: kangasta
  password:
    secure: XyrVHTVKF98l65f7VzJ8/974IXDkzhE7Wffme5arbpnf7JlsLJRlO+qXwCVEnFxxTIL5D25ZhnQBrX8Cxk1KR1FJlsru/9EGEYSWL5BJ6TllnQqdlzghpGN1JZr7Qs1wQLVY+KRc1xjthFmBeZx9PeIhWSQrAmo+nimGJP+Ab+9XfslOTz2o7NxUqJ/Rh2HpHtZXqZ+ZxxA+yWqD+NaRQ6mXDAT5KKqo8UByoXO3ehKuLF9Bef21Dv31mbpEH9DeDoepamVKEeIis6r9aWx4B19H/u6QYGh7wfqOexx/4cPhPmPYMHB5/3TINaNWllzW06cZNRPUCOaY7oJ4zt956JWSiBWws1zPtJ+ecFU8BPnsTaceLIXCYPdd04MAme9EuTgHg9B2Qo8MI/+NwpdnWrDBChCfZIGG22mm6w+iRGi9Wtm3lznzrKz1nl/3nqHLln9CBgtv8Wd+y+BUmh+WwHsGj4SqGQZe/3cB69ArXpmKW3oRazl44Ob/N6/4VMjszYhSa2wodznkl9c21NdChYe1vkZNdPCBYBixrOjP5EnLqMdlFQt8sA31rSG16vdC3BTnQGYPL413fsVpUgnuG6lpx7hYTjl3PZrZe69a5GUPI0+tHQ7JH9BoguioLZ+3pNWXruz2YyqKrlPjxLWZi9IW+dab8/Dx0ysJcz9ql5s=
  on:
    tags: true
    python: 3.6
